systemLog:
  verbosity: 1
  destination: file
  path: "./eloqdoc_test/log.json"
  component:
    ftdc:
      verbosity: 0
net:
  port: 27017
  bindIp: "0.0.0.0"
  serviceExecutor: "adaptive"
storage:
  dbPath: "./eloqdoc_test"
  engine: "eloq"
  eloq:
    enableCoroutine: true
    reservedThreadNum: 2
    adaptiveThreadNum: 1
    txService:
      # localIP: "127.0.0.1:10000"
      # ipList: ["127.0.0.1:10000"]
      checkpointerIntervalSec: 10
      nodeMemoryLimitMB: 8192
      realtimeSampling: true
      collectActiveTxTsIntervalSec: 2
      checkpointerDelaySec: 5
      ccProtocol: "OCC"
      # txlogServiceList: ["127.0.0.1:8500"]
      # txlogGroupReplicaNum: 1
      # skipRedoLog: true
      txlogRocksDBStoragePath: "./eloqdoc_test/log_service_rocksdb"
    metrics:
      enableMetrics: true
      metricsPort: 18081
      enableMemoryUsage: true
      collectMemoryUsageRound: 10000
      enableCacheHitRate: true
      enableTxMetrics: true
      collectTxDurationRound: 100
      enableBusyRoundMetrics: true
      busyRoundThreshold: 10
    storage:
      dataStoreServiceConfigFilePath: ""
      # dssPeerNode: "127.0.0.1:9100"
      rocksdbCloudStoragePath: "./eloqdoc_test/dss_rocksdb_cloud"
      rocksdbCloudSstFileCacheSize: "5GB"
      awsAccessKeyId: "pstJJurylOvuNpIJacG7"
      awsSecretKey: "d78pZI8btixlnC7kHhtjEX573paLSm9R2lWwVfmu"
      rocksdbCloudBucketName: "eloqdoc-storage"
      rocksdbCloudBucketPrefix: "rocksdb-cloud-"
      rocksdbCloudObjectPath: "eloqdoc_db"
      rocksdbCloudRegion: "ap-northeast-1"
      rocksdbCloudEndpointUrl: "http://127.0.0.1:9000"

setParameter:
  diagnosticDataCollectionEnabled: false
  disableLogicalSessionCacheRefresh: true
  ttlMonitorEnabled: false
