systemLog:
  verbosity: 1
  destination: file
  path: "/home/starrysky/workspace/mongo/test_eloqdoc/node2/log.json"
  component:
    ftdc:
      verbosity: 0
net:
  bindIp: "0.0.0.0"
  port: 27027
  serviceExecutor: "adaptive"
storage:
  dbPath: "/home/starrysky/workspace/mongo/test_eloqdoc/node2"
  engine: "eloq"
  eloq:
    enableCoroutine: true
    reservedThreadNum: 2
    adaptiveThreadNum: 5
    txService:
      localIP: "127.0.0.1:10200"
      ipList: ["127.0.0.1:10000", "127.0.0.1:10100", "127.0.0.1:10200"]
      checkpointerIntervalSec: 10
      nodeMemoryLimitMB: 8192
      realtimeSampling: true
      collectActiveTxTsIntervalSec: 2
      checkpointerDelaySec: 5
      ccProtocol: "OCC"
      txlogServiceList: ["127.0.0.1:8500"]
      txlogGroupReplicaNum: 1
      # skipRedoLog: true
    metrics:
      enableMetrics: true
      metricsPort: 18083
      enableMemoryUsage: true
      collectMemoryUsageRound: 10000
      enableCacheHitRate: true
      enableTxMetrics: true
      collectTxDurationRound: 100
      enableBusyRoundMetrics: true
      busyRoundThreshold: 10
    storage:
      # dataStoreServiceConfigFilePath: "/home/starrysky/workspace/mongo/config/dss_config.ini"
      dssPeerNode: "127.0.0.1:9100"
      awsAccessKeyId: "pstJJurylOvuNpIJacG7"
      awsSecretKey: "d78pZI8btixlnC7kHhtjEX573paLSm9R2lWwVfmu"
      rocksdbCloudBucketName: "eloqdoc-storage2"
      rocksdbCloudBucketPrefix: "rocksdb-cloud-"
      rocksdbCloudObjectPath: "eloqdoc_db"
      rocksdbCloudRegion: "ap-northeast-1"
      rocksdbCloudEndpointUrl: "http://127.0.0.1:9000"

setParameter:
  diagnosticDataCollectionEnabled: false
  disableLogicalSessionCacheRefresh: true
  ttlMonitorEnabled: false
